### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by rafia9005** [khilmeee/TokoElektro#3]

**Comment by rafia9005** [comment]
![2024-05-02-211405_hyprshot](https://github.com/khilmeee/TokoElektro/assets/70046808/8087d40c-1a7a-4771-aa0c-cd933ff7bb90)
cara install nya compile nya begimana? kalo di arch?

**Comment by miwone** [comment]
Ga support di Linux keknya, harus make visual studio

**Comment by rafia9005** [comment]
aku ada visual studio ini, apakah bisa yak. wet tak coba
